from PyQt5 import QtCore, QtGui, QtWidgets

class uiForLogIn(object):
    def setupUi(self, LogIn):
        LogIn.setObjectName("LogIn")
        LogIn.resize(1391, 847)
        self.centralwidget = QtWidgets.QWidget(LogIn)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{background:rgb(255, 255, 255)}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setMinimumSize(QtCore.QSize(800, 800))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget_4)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setMinimumSize(QtCore.QSize(100, 120))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_start = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_2.addWidget(self.pushButton_start)
        self.pushButton_pause = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_pause.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_pause.setFont(font)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout_2.addWidget(self.pushButton_pause)
        self.pushButton_stop = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_2.addWidget(self.pushButton_stop)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.lcdNumber_time = QtWidgets.QLCDNumber(self.widget_6)
        self.lcdNumber_time.setMinimumSize(QtCore.QSize(100, 50))
        self.lcdNumber_time.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lcdNumber_time.setFont(font)
        self.lcdNumber_time.setObjectName("lcdNumber_time")
        self.verticalLayout_4.addWidget(self.lcdNumber_time, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.lcdNumber_score = QtWidgets.QLCDNumber(self.widget_5)
        self.lcdNumber_score.setMinimumSize(QtCore.QSize(100, 50))
        self.lcdNumber_score.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lcdNumber_score.setFont(font)
        self.lcdNumber_score.setObjectName("lcdNumber_score")
        self.verticalLayout_3.addWidget(self.lcdNumber_score, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(560, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_cap = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.label_cap.sizePolicy().hasHeightForWidth())
        self.label_cap.setSizePolicy(sizePolicy)
        self.label_cap.setMinimumSize(QtCore.QSize(480, 360))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cap.setFont(font)
        self.label_cap.setText("")
        self.label_cap.setObjectName("label_cap")
        self.verticalLayout.addWidget(self.label_cap, 0, QtCore.Qt.AlignHCenter)
        self.label_picture = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label_picture.sizePolicy().hasHeightForWidth())
        self.label_picture.setSizePolicy(sizePolicy)
        self.label_picture.setMinimumSize(QtCore.QSize(540, 360))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.horizontalLayout.addWidget(self.widget)
        LogIn.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LogIn)
        self.statusbar.setObjectName("statusbar")
        LogIn.setStatusBar(self.statusbar)

        self.retranslateUi(LogIn)
        QtCore.QMetaObject.connectSlotsByName(LogIn)

    def retranslateUi(self, LogIn):
        _translate = QtCore.QCoreApplication.translate
        LogIn.setWindowTitle(_translate("LogIn", "MainWindow"))
        self.pushButton_start.setText(_translate("LogIn", "开始"))
        self.pushButton_pause.setText(_translate("LogIn", "暂停"))
        self.pushButton_stop.setText(_translate("LogIn", "停止"))
        self.label.setText(_translate("LogIn", "时间"))
        self.label_2.setText(_translate("LogIn", "得分"))
